package com.myexample.dao;

import com.myexample.model.po.Fruit;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;

@Mapper
public interface FruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated
     */
    int insert(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated
     */
    int insertSelective(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated
     */
    Fruit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fruit record);

    ArrayList<Fruit> getAll();

    ArrayList<Fruit> query(@Param("query")Fruit fruit);
}